version: '3.8'

services:
  flask_app:
    build: ./Digitalizing-PaperWork-Paperless-
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=mydatabase
    volumes:
      - flask_app_data:/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  flask_app_data:
