"""little changes

Revision ID: 0829041abad1
Revises: 8ea4f9dc0ed6
Create Date: 2024-04-15 16:31:54.093825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0829041abad1'
down_revision = '8ea4f9dc0ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=20), nullable=False))
        batch_op.drop_column('operator_employee_id')

    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=20), nullable=False))
        batch_op.drop_column('operator_employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_employee_id', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('station_id')

    with op.batch_alter_table('reading_params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_employee_id', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('station_id')

    # ### end Alembic commands ###
