"""little changes

Revision ID: 0e63a2bac770
Revises: 564effee01f5
Create Date: 2024-04-12 18:22:45.476304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e63a2bac770'
down_revision = '564effee01f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.alter_column('status_datas',
               existing_type=mysql.VARCHAR(length=1500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.alter_column('status_datas',
               existing_type=mysql.VARCHAR(length=1500),
               nullable=False)

    # ### end Alembic commands ###
