"""little changes

Revision ID: 10a13780c6aa
Revises: acea0f6e95f8
Create Date: 2024-05-31 14:51:25.898129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10a13780c6aa'
down_revision = 'acea0f6e95f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.alter_column('shift_A',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('shift_B',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('shift_C',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.alter_column('shift_C',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('shift_B',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('shift_A',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###
