"""little changes

Revision ID: 1399328ed5d5
Revises: fa12b5c81f95
Create Date: 2024-04-26 10:43:58.326302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1399328ed5d5'
down_revision = 'fa12b5c81f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records_logs', schema=None) as batch_op:
        batch_op.drop_column('logs_date')

    # ### end Alembic commands ###
