"""little changes

Revision ID: 1810533c3686
Revises: bbc5fa0afaae
Create Date: 2024-03-19 16:00:07.583598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1810533c3686'
down_revision = 'bbc5fa0afaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts_info', schema=None) as batch_op:
        batch_op.drop_column('images_paths')

    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_urls', sa.String(length=1200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.drop_column('images_urls')

    with op.batch_alter_table('parts_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_paths', mysql.VARCHAR(length=1200), nullable=True))

    # ### end Alembic commands ###
