"""little changes

Revision ID: 1d586887c58f
Revises: 264c460333f0
Create Date: 2024-04-12 17:50:10.184890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d586887c58f'
down_revision = '264c460333f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.alter_column('station_id',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.alter_column('station_id',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
