"""added some tables in database

Revision ID: 258484a86d13
Revises: 
Create Date: 2024-03-12 14:54:44.217336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258484a86d13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_operators_logged_in_status',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('operator_username', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=14), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=False),
    sa.Column('login_status', sa.Boolean(), nullable=True),
    sa.Column('first_login_time', sa.Date(), nullable=True),
    sa.Column('last_login_time', sa.Date(), nullable=True),
    sa.Column('logout_time', sa.Date(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('all_part_no_and_name_info',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('part_name', sa.String(length=36), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('all_sites_information',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_location', sa.String(length=25), nullable=False),
    sa.Column('building_no', sa.String(length=16), nullable=False),
    sa.Column('floor_no', sa.String(length=16), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('station_no', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('app_id_with_user_type',
    sa.Column('app_id', sa.String(length=50), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('app_id'),
    sa.UniqueConstraint('app_id')
    )
    op.create_table('floor_incharge_creds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('employee_id', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('building_no', sa.String(length=30), nullable=False),
    sa.Column('floor_no', sa.String(length=10), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('fName', sa.String(length=15), nullable=False),
    sa.Column('mName', sa.String(length=15), nullable=True),
    sa.Column('lName', sa.String(length=15), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('gurugram_assigned_task_by_admin',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('building_no', sa.String(length=16), nullable=False),
    sa.Column('floor_no', sa.String(length=16), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('app_id', sa.String(length=20), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=False),
    sa.Column('operator_username', sa.String(length=80), nullable=False),
    sa.Column('assigned_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('gurugram_line_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.String(length=20), nullable=True),
    sa.Column('target', sa.String(length=15), nullable=True),
    sa.Column('passed', sa.String(length=15), nullable=True),
    sa.Column('failed', sa.String(length=15), nullable=True),
    sa.Column('filled', sa.String(length=15), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gurugram_station_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sift', sa.String(length=10), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=15), nullable=True),
    sa.Column('passed', sa.String(length=15), nullable=True),
    sa.Column('failed', sa.String(length=15), nullable=True),
    sa.Column('filled', sa.String(length=15), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_creds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('fName', sa.String(length=15), nullable=False),
    sa.Column('mName', sa.String(length=15), nullable=True),
    sa.Column('lName', sa.String(length=15), nullable=True),
    sa.Column('skill_level', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('parameters_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('parameter_name', sa.String(length=120), nullable=False),
    sa.Column('parameter_no', sa.String(length=60), nullable=False),
    sa.Column('process_no', sa.String(length=40), nullable=False),
    sa.Column('belongs_to_part', sa.String(length=20), nullable=False),
    sa.Column('added_by_owner', sa.String(length=30), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('parameter_no')
    )
    op.create_table('parts_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('parn_name', sa.String(length=64), nullable=False),
    sa.Column('part_no', sa.String(length=20), nullable=False),
    sa.Column('added_by_owner', sa.String(length=30), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('part_no')
    )
    op.create_table('processes_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('process_name', sa.String(length=120), nullable=False),
    sa.Column('process_no', sa.String(length=40), nullable=False),
    sa.Column('belongs_to_part', sa.String(length=20), nullable=False),
    sa.Column('added_by_owner', sa.String(length=30), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('process_no')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('station_id', sa.String(length=15), nullable=False),
    sa.Column('line_no', sa.String(length=10), nullable=False),
    sa.Column('floor_no', sa.String(length=10), nullable=False),
    sa.Column('building_no', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=25), nullable=False),
    sa.Column('added_by_owner', sa.String(length=15), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_table('unregister_user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('ServTimeStemp', sa.DateTime(), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('work_assigned_to_operator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id_id', sa.String(length=20), nullable=False),
    sa.Column('station_id', sa.String(length=15), nullable=False),
    sa.Column('part_no', sa.String(length=20), nullable=False),
    sa.Column('process_no', sa.String(length=20), nullable=False),
    sa.Column('start_shift_time', sa.Time(), nullable=False),
    sa.Column('end_shift_time', sa.Time(), nullable=False),
    sa.Column('assigned_by_owner', sa.String(length=30), nullable=False),
    sa.Column('operator_login_status', sa.Boolean(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_assigned_to_operator_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id_id', sa.String(length=20), nullable=False),
    sa.Column('station_id', sa.String(length=15), nullable=False),
    sa.Column('part_no', sa.String(length=20), nullable=False),
    sa.Column('process_no', sa.String(length=20), nullable=False),
    sa.Column('start_shift_time', sa.Time(), nullable=False),
    sa.Column('end_shift_time', sa.Time(), nullable=False),
    sa.Column('assigned_by_owner', sa.String(length=30), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_assigned_to_operator_logs')
    op.drop_table('work_assigned_to_operator')
    op.drop_table('unregister_user')
    op.drop_table('stations')
    op.drop_table('processes_info')
    op.drop_table('parts_info')
    op.drop_table('parameters_info')
    op.drop_table('operator_creds')
    op.drop_table('gurugram_station_performance')
    op.drop_table('gurugram_line_performance')
    op.drop_table('gurugram_assigned_task_by_admin')
    op.drop_table('floor_incharge_creds')
    op.drop_table('app_id_with_user_type')
    op.drop_table('all_sites_information')
    op.drop_table('all_part_no_and_name_info')
    op.drop_table('all_operators_logged_in_status')
    # ### end Alembic commands ###
