"""Change Intiger to String all_floor_incharge

Revision ID: 274823d8596a
Revises: 5c3ca62a0000
Create Date: 2023-12-23 10:05:21.336264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274823d8596a'
down_revision = '5c3ca62a0000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_floor_incharge', schema=None) as batch_op:
        batch_op.alter_column('floor_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_floor_incharge', schema=None) as batch_op:
        batch_op.alter_column('floor_no',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
