"""little changes

Revision ID: 2e405e060691
Revises: 
Create Date: 2024-06-03 14:22:33.205921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e405e060691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_data')
    op.drop_table('parts')
    op.drop_table('parameters')
    op.drop_table('task_assigned')
    with op.batch_alter_table('params_ucl_lcl', schema=None) as batch_op:
        batch_op.drop_column('A2')
        batch_op.drop_column('D4')
        batch_op.drop_column('D3')
        batch_op.drop_column('D2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('params_ucl_lcl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('D2', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('D3', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('D4', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('A2', mysql.FLOAT(), nullable=True))

    op.create_table('task_assigned',
    sa.Column('task_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('floor_id', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('line_id', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('part_id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('part_name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('prev_quantity', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('quantity', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('assigned_for_date', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('is_task_completed', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('parts_completed', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('parts_filled', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('parts_passed', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('parts_failed', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('approved', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('parameters',
    sa.Column('parm_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('process_id', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('param_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('min', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('max', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('isfillable', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('parm_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('parts',
    sa.Column('part_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('floor_id', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('part_name', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('part_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('process_data',
    sa.Column('process_data_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('process_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('station_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('timestamp', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('p1', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('p2', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('process_data_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
