"""little changes

Revision ID: 2fe559333032
Revises: d61c9411eec5
Create Date: 2024-04-27 11:42:24.438617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe559333032'
down_revision = 'd61c9411eec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.alter_column('assigned_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.alter_column('assigned_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
