"""little changes

Revision ID: 30379f1cce6d
Revises: ac2b33c1f708
Create Date: 2024-05-01 11:31:30.116545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30379f1cce6d'
down_revision = 'ac2b33c1f708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor_no', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('floor_incharge_id', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reasons', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('date')
        batch_op.drop_column('floor_incharge_id')
        batch_op.drop_column('floor_no')

    # ### end Alembic commands ###
