"""stations_info and stations_info_log tables commented

Revision ID: 3843f912fa61
Revises: 5e004f4799a7
Create Date: 2024-03-19 11:33:18.126295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3843f912fa61'
down_revision = '5e004f4799a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_info')
    op.drop_table('station_info_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_info_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_id', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('total_assigned_task', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('left_for_rework', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filled', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_shift_timing', mysql.TIME(), nullable=False),
    sa.Column('end_shift_timing', mysql.TIME(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('station_info',
    sa.Column('station_id', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('total_assigned_task', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('left_for_rework', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('passed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filled', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_shift_timing', mysql.TIME(), nullable=False),
    sa.Column('end_shift_timing', mysql.TIME(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('station_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
