"""little changes

Revision ID: 4b1041b6c561
Revises: 5d536efd6f7b
Create Date: 2024-05-24 15:27:20.374965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1041b6c561'
down_revision = '5d536efd6f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('log_date', sa.Date(), nullable=True))

    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processes_info_belongs_to_part'), ['belongs_to_part'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processes_info_belongs_to_part'))

    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.drop_column('log_date')
        batch_op.drop_column('log_time')

    # ### end Alembic commands ###
