"""Initial Migration

Revision ID: 4b69aea1baa5
Revises: 
Create Date: 2023-12-15 20:11:04.574083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b69aea1baa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_id_with_user_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['app_id'])

    with op.batch_alter_table('operator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator', schema=None) as batch_op:
        batch_op.drop_column('app_id')

    with op.batch_alter_table('app_id_with_user_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
