"""little changes

Revision ID: 4ec0dabee30d
Revises: 79351d7e1d45
Create Date: 2024-03-27 15:28:13.240428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec0dabee30d'
down_revision = '79351d7e1d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_to_incharge',
    sa.Column('station_id', sa.String(length=25), nullable=False),
    sa.Column('csp_id', sa.Integer(), nullable=False),
    sa.Column('floor_no', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('station_id', 'csp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notify_to_incharge')
    # ### end Alembic commands ###
