"""Added the process_no in reasons table

Revision ID: 545eeef37f6f
Revises: dd8899334dd0
Create Date: 2024-06-08 10:08:15.025727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '545eeef37f6f'
down_revision = 'dd8899334dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cycle_Time_secs', sa.Integer(), nullable=True))
        batch_op.drop_column('station_id')
        batch_op.drop_column('avg_minutes_to_complete')
        batch_op.drop_column('shift')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', mysql.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('avg_minutes_to_complete', mysql.VARCHAR(length=3), nullable=True))
        batch_op.add_column(sa.Column('station_id', mysql.VARCHAR(length=25), nullable=True))
        batch_op.drop_column('Cycle_Time_secs')

    # ### end Alembic commands ###
