"""Created some database

Revision ID: 5c3ca62a0000
Revises: 59b8dcc2f998
Create Date: 2023-12-23 08:28:55.193921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c3ca62a0000'
down_revision = '59b8dcc2f998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all__operator_creds',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('app_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('all_floor_incharge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('building_no', sa.String(length=30), nullable=False),
    sa.Column('floor_no', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('all_operators_logged_in_status',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('operator_username', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=14), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=False),
    sa.Column('login_status', sa.Boolean(), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('all_part_no_and_name_info',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('part_name', sa.String(length=36), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('all_sites_information',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_location', sa.String(length=25), nullable=False),
    sa.Column('building_no', sa.String(length=16), nullable=False),
    sa.Column('floor_no', sa.String(length=16), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('station_no', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('gurugram_assigned_task_by_admin',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('building_no', sa.String(length=16), nullable=False),
    sa.Column('floor_no', sa.String(length=16), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('app_id', sa.String(length=20), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=False),
    sa.Column('operator_username', sa.String(length=80), nullable=False),
    sa.Column('assigned_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('gurugram_line_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.String(length=20), nullable=True),
    sa.Column('target', sa.String(length=15), nullable=True),
    sa.Column('passed', sa.String(length=15), nullable=True),
    sa.Column('failed', sa.String(length=15), nullable=True),
    sa.Column('filled', sa.String(length=15), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gurugram_station_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=True),
    sa.Column('target', sa.String(length=15), nullable=True),
    sa.Column('passed', sa.String(length=15), nullable=True),
    sa.Column('failed', sa.String(length=15), nullable=True),
    sa.Column('filled', sa.String(length=15), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assigned_task_by_admin')
    op.drop_table('floor_incharge')
    op.drop_table('sites_information')
    op.drop_table('part_no_and_name_info')
    op.drop_table('operator_creds')
    op.drop_table('operators_logged_in_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators_logged_in_status',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('line_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('station_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('login_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name='operators_logged_in_status_pkey')
    )
    op.create_table('operator_creds',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=14), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('app_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='operator_creds_pkey'),
    sa.UniqueConstraint('email', name='operator_creds_email_key'),
    sa.UniqueConstraint('mobile', name='operator_creds_mobile_key'),
    sa.UniqueConstraint('username', name='operator_creds_username_key')
    )
    op.create_table('part_no_and_name_info',
    sa.Column('part_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('part_name', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('process_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('part_id', name='part_no_and_name_info_pkey')
    )
    op.create_table('sites_information',
    sa.Column('site_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_location', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('building_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('floor_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('line_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('station_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('site_id', name='sites_information_pkey')
    )
    op.create_table('floor_incharge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('floor_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('building_no', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='floor_incharge_pkey'),
    sa.UniqueConstraint('user_name', name='floor_incharge_user_name_key')
    )
    op.create_table('assigned_task_by_admin',
    sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('process_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('building_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('floor_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('line_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('station_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('operator_username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('assigned_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('task_id', name='assigned_task_by_admin_pkey')
    )
    op.drop_table('gurugram_station_performance')
    op.drop_table('gurugram_line_performance')
    op.drop_table('gurugram_assigned_task_by_admin')
    op.drop_table('all_sites_information')
    op.drop_table('all_part_no_and_name_info')
    op.drop_table('all_operators_logged_in_status')
    op.drop_table('all_floor_incharge')
    op.drop_table('all__operator_creds')
    # ### end Alembic commands ###
