"""little changes

Revision ID: 687f7439dd82
Revises: c65228007959
Create Date: 2024-03-22 15:44:21.941968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '687f7439dd82'
down_revision = 'c65228007959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet', schema=None) as batch_op:
        batch_op.alter_column('csp_id',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=15), nullable=False))
        batch_op.alter_column('oprtr_employee_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['oprtr_employee_id'])

    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=15), nullable=False))
        batch_op.create_index(batch_op.f('ix_check_sheet_data_logs_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_sheet_data_logs_station_id'))
        batch_op.drop_column('station_id')

    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('oprtr_employee_id',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('station_id')

    with op.batch_alter_table('check_sheet', schema=None) as batch_op:
        batch_op.alter_column('csp_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
