"""Major update in database model and many are created

Revision ID: 719f8f401112
Revises: 602bc8a89b48
Create Date: 2023-12-19 20:18:29.879317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719f8f401112'
down_revision = '602bc8a89b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_task_by_admin',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('building_no', sa.String(length=16), nullable=False),
    sa.Column('floor_no', sa.String(length=16), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('app_id', sa.String(length=20), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=False),
    sa.Column('operator_username', sa.String(length=80), nullable=False),
    sa.Column('assigned_time', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('operators_logged_in_status',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('operator_username', sa.String(length=80), nullable=False),
    sa.Column('mobile', sa.String(length=14), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('station_no', sa.String(length=20), nullable=False),
    sa.Column('login_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('part_no_and_name_info',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=16), nullable=False),
    sa.Column('part_name', sa.String(length=36), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('sites_information',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_location', sa.String(length=25), nullable=False),
    sa.Column('building_no', sa.String(length=16), nullable=False),
    sa.Column('floor_no', sa.String(length=16), nullable=False),
    sa.Column('line_no', sa.String(length=16), nullable=False),
    sa.Column('station_no', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites_information')
    op.drop_table('part_no_and_name_info')
    op.drop_table('operators_logged_in_status')
    op.drop_table('assigned_task_by_admin')
    # ### end Alembic commands ###
