"""little changes

Revision ID: 72715153a4d9
Revises: 92ba5177580a
Create Date: 2024-04-17 11:32:43.213808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72715153a4d9'
down_revision = '92ba5177580a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skill_level', sa.Integer(), nullable=True))
        batch_op.drop_column('required_skill_lavel')

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_end_shift_time'), ['end_shift_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_start_shift_time'), ['start_shift_time'], unique=False)

    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_logs_end_shift_time'), ['end_shift_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_logs_start_shift_time'), ['start_shift_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_logs_start_shift_time'))
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_logs_end_shift_time'))

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_start_shift_time'))
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_end_shift_time'))

    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skill_lavel', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('required_skill_level')

    # ### end Alembic commands ###
