"""little changes

Revision ID: 77eac5bbf014
Revises: 0e63a2bac770
Create Date: 2024-04-12 18:23:47.989114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77eac5bbf014'
down_revision = '0e63a2bac770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.alter_column('status_datas',
               existing_type=mysql.VARCHAR(length=1500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.alter_column('status_datas',
               existing_type=mysql.VARCHAR(length=1500),
               nullable=False)

    # ### end Alembic commands ###
