"""little changes

Revision ID: 79ca1d67fd94
Revises: 2e405e060691
Create Date: 2024-06-06 10:11:07.047904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ca1d67fd94'
down_revision = '2e405e060691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notify_to_incharge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notify_to_incharge', schema=None) as batch_op:
        batch_op.drop_column('approved_status')

    # ### end Alembic commands ###
