"""little changes

Revision ID: 7f2a1db8f5e1
Revises: ab4a37c6598d
Create Date: 2024-03-19 17:03:54.488579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f2a1db8f5e1'
down_revision = 'ab4a37c6598d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csp_name_hindi', sa.String(length=250), nullable=True))
        batch_op.drop_column('param_value_hindi')
        batch_op.drop_column('param_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('param_value', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('param_value_hindi', mysql.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('csp_name_hindi')

    # ### end Alembic commands ###
