"""remove id column in operator_creds table

Revision ID: 88f14a5fcf2b
Revises: 0acc7a0f37e8
Create Date: 2024-03-12 16:23:04.344922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88f14a5fcf2b'
down_revision = '0acc7a0f37e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
