"""little changes

Revision ID: 8f46a599cb88
Revises: d3c8703154b2
Create Date: 2024-04-30 11:00:32.690675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f46a599cb88'
down_revision = 'd3c8703154b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.drop_column('logs_date')

    # ### end Alembic commands ###
