"""little changes

Revision ID: 90304f5181bc
Revises: 9c05df2bb7f7
Create Date: 2024-05-31 12:14:16.337543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90304f5181bc'
down_revision = '9c05df2bb7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_A', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('shift_B', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('shift_C', sa.String(length=2), nullable=True))
        batch_op.drop_column('shift')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', mysql.VARCHAR(length=2), nullable=True))
        batch_op.drop_column('shift_C')
        batch_op.drop_column('shift_B')
        batch_op.drop_column('shift_A')

    # ### end Alembic commands ###
