"""little changes

Revision ID: 92ba5177580a
Revises: 0829041abad1
Create Date: 2024-04-16 12:25:59.090350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ba5177580a'
down_revision = '0829041abad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skill_lavel', sa.Integer(), nullable=True))

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.drop_index('process_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.create_index('process_no', ['process_no'], unique=True)

    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.drop_column('required_skill_lavel')

    # ### end Alembic commands ###
