"""little changes

Revision ID: 9506b9b4881f
Revises: c472ba6bf664
Create Date: 2024-05-16 10:47:40.233008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9506b9b4881f'
down_revision = 'c472ba6bf664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('params_ucl_lcl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('USL', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('LSL', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('A2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('D2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('D3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('D4', sa.Float(), nullable=True))
        batch_op.drop_column('UCL')
        batch_op.drop_column('LCL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('params_ucl_lcl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LCL', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('UCL', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('D4')
        batch_op.drop_column('D3')
        batch_op.drop_column('D2')
        batch_op.drop_column('A2')
        batch_op.drop_column('LSL')
        batch_op.drop_column('USL')

    # ### end Alembic commands ###
