"""little changes

Revision ID: 9c05df2bb7f7
Revises: 4b1041b6c561
Create Date: 2024-05-30 16:54:41.890583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c05df2bb7f7'
down_revision = '4b1041b6c561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('shift', sa.String(length=2), nullable=True))

    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('shift', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('avg_minutes_to_complete', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.drop_column('avg_minutes_to_complete')
        batch_op.drop_column('shift')
        batch_op.drop_column('station_id')

    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.drop_column('shift')
        batch_op.drop_column('station_id')

    # ### end Alembic commands ###
