"""little changes

Revision ID: a585f2eb37e4
Revises: d7cc7602cf40
Create Date: 2024-03-22 11:21:58.768665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a585f2eb37e4'
down_revision = 'd7cc7602cf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('disable')

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('parts_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('disabled')

    # ### end Alembic commands ###
