"""little changes

Revision ID: a9426a45f888
Revises: cfe6bb679546
Create Date: 2024-05-22 15:15:06.188325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9426a45f888'
down_revision = 'cfe6bb679546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_task_id'))

    # ### end Alembic commands ###
