"""little changes

Revision ID: a9dde70c3b21
Revises: 1399328ed5d5
Create Date: 2024-04-26 10:45:10.719701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9dde70c3b21'
down_revision = '1399328ed5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records_logs', schema=None) as batch_op:
        batch_op.alter_column('start_shift_1_parameters_values',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=1500),
               existing_nullable=True)
        batch_op.alter_column('start_shift_2_parameters_values',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=1500),
               existing_nullable=True)
        batch_op.alter_column('end_shift_1_parameters_values',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=1500),
               existing_nullable=True)
        batch_op.alter_column('end_shift_2_parameters_values',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records_logs', schema=None) as batch_op:
        batch_op.alter_column('end_shift_2_parameters_values',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('end_shift_1_parameters_values',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('start_shift_2_parameters_values',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('start_shift_1_parameters_values',
               existing_type=sa.String(length=1500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
