"""little changes

Revision ID: ab4a37c6598d
Revises: 18b81a8eae68
Create Date: 2024-03-19 16:57:06.416817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4a37c6598d'
down_revision = '18b81a8eae68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('control_method', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('param_value', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('param_value_hindi', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet', schema=None) as batch_op:
        batch_op.drop_column('param_value_hindi')
        batch_op.drop_column('param_value')
        batch_op.drop_column('frequency')
        batch_op.drop_column('control_method')
        batch_op.drop_column('specification')

    # ### end Alembic commands ###
