"""little changes

Revision ID: ac2b33c1f708
Revises: 7944a6e37cc6
Create Date: 2024-05-01 11:26:14.535384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2b33c1f708'
down_revision = '7944a6e37cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notify_to_incharge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notify_to_incharge_csp_id'), ['csp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notify_to_incharge_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notify_to_incharge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notify_to_incharge_station_id'))
        batch_op.drop_index(batch_op.f('ix_notify_to_incharge_csp_id'))

    # ### end Alembic commands ###
