"""little changes

Revision ID: acea0f6e95f8
Revises: 7b1ce0b3ae0d
Create Date: 2024-05-31 12:49:55.532223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acea0f6e95f8'
down_revision = '7b1ce0b3ae0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_creds_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_creds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_creds_station_id'))

    # ### end Alembic commands ###
