"""little changes

Revision ID: b8ab8aba8600
Revises: eac439ca43eb
Create Date: 2024-04-12 17:53:02.588368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ab8aba8600'
down_revision = 'eac439ca43eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.drop_index('oprtr_employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.create_index('oprtr_employee_id', ['oprtr_employee_id'], unique=True)

    # ### end Alembic commands ###
