"""little changes

Revision ID: bbc5fa0afaae
Revises: 3843f912fa61
Create Date: 2024-03-19 12:22:20.653506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc5fa0afaae'
down_revision = '3843f912fa61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_paths', sa.String(length=1200), nullable=True))

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.drop_column('time')

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.drop_column('time')

    with op.batch_alter_table('parts_info', schema=None) as batch_op:
        batch_op.drop_column('images_paths')

    # ### end Alembic commands ###
