"""little changes

Revision ID: bc782f65ffae
Revises: 77eac5bbf014
Create Date: 2024-04-15 10:54:31.867621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc782f65ffae'
down_revision = '77eac5bbf014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('part_no', sa.String(length=20), nullable=False))
        batch_op.drop_index('ix_fpa_and_set_up_approved_records_operator_employee_id')
        batch_op.create_index(batch_op.f('ix_fpa_and_set_up_approved_records_station_id'), ['station_id'], unique=False)
        batch_op.drop_column('operator_employee_id')

    with op.batch_alter_table('fpa_and_set_up_approved_records_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('part_no', sa.String(length=20), nullable=False))
        batch_op.drop_column('operator_employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_employee_id', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('part_no')
        batch_op.drop_column('station_id')

    with op.batch_alter_table('fpa_and_set_up_approved_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_employee_id', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_fpa_and_set_up_approved_records_station_id'))
        batch_op.create_index('ix_fpa_and_set_up_approved_records_operator_employee_id', ['operator_employee_id'], unique=False)
        batch_op.drop_column('part_no')
        batch_op.drop_column('station_id')

    # ### end Alembic commands ###
