"""little changes

Revision ID: c472ba6bf664
Revises: d79b8f9e969e
Create Date: 2024-05-06 13:03:45.870506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c472ba6bf664'
down_revision = 'd79b8f9e969e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.drop_column('shift')

    # ### end Alembic commands ###
