"""little changes

Revision ID: c4ae2c645ca3
Revises: 2fe559333032
Create Date: 2024-04-27 11:43:03.987087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ae2c645ca3'
down_revision = '2fe559333032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_logs_assigned_date'), ['assigned_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_logs_assigned_date'))

    # ### end Alembic commands ###
