"""little changes

Revision ID: c65228007959
Revises: a585f2eb37e4
Create Date: 2024-03-22 12:32:00.524705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c65228007959'
down_revision = 'a585f2eb37e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.drop_column('csp_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_sheet_data_logs_oprtr_employee_id'), ['oprtr_employee_id'], unique=False)
        batch_op.drop_column('csp_id')

    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_logs_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_logs_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_logs_station_id'))
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_logs_employee_id'))

    with op.batch_alter_table('check_sheet_data_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csp_id', mysql.VARCHAR(length=15), nullable=False))
        batch_op.drop_index(batch_op.f('ix_check_sheet_data_logs_oprtr_employee_id'))

    with op.batch_alter_table('check_sheet_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('csp_id', mysql.VARCHAR(length=15), nullable=False))

    # ### end Alembic commands ###
