"""little changes

Revision ID: c8ef8b504ddb
Revises: 13195788f807
Create Date: 2024-04-15 11:18:02.353691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8ef8b504ddb'
down_revision = '13195788f807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at_mid_shift', sa.Integer(), nullable=True))
        batch_op.drop_column('left_for_rework')

    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at_mid_shift', sa.Integer(), nullable=True))
        batch_op.drop_column('left_for_rework')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_for_rework', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('completed_at_mid_shift')

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_for_rework', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('completed_at_mid_shift')

    # ### end Alembic commands ###
