"""little changes

Revision ID: cfe6bb679546
Revises: 9506b9b4881f
Create Date: 2024-05-22 13:15:00.509825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe6bb679546'
down_revision = '9506b9b4881f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_precedency', sa.Integer(), nullable=False))

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('station_precedency', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_work_assigned_to_operator_part_no'), ['part_no'], unique=False)

    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_precedency', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.drop_column('station_precedency')

    with op.batch_alter_table('work_assigned_to_operator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_assigned_to_operator_part_no'))
        batch_op.drop_column('station_precedency')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('processes_info', schema=None) as batch_op:
        batch_op.drop_column('process_precedency')

    # ### end Alembic commands ###
