"""little changes

Revision ID: d3c8703154b2
Revises: 4d8fa28f332e
Create Date: 2024-04-29 17:03:21.522784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3c8703154b2'
down_revision = '4d8fa28f332e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.alter_column('reading_1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('reading_1_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('reading_2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('reading_2_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('reading_3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('reading_3_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('reading_4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('reading_4_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('reading_5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('reading_5_time',
               existing_type=mysql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.alter_column('reading_5_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('reading_5',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('reading_4_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('reading_4',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('reading_3_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('reading_3',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('reading_2_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('reading_2',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('reading_1_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('reading_1',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
