"""little changes

Revision ID: d61c9411eec5
Revises: a9dde70c3b21
Create Date: 2024-04-27 11:33:42.443445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61c9411eec5'
down_revision = 'a9dde70c3b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('logs_date', sa.Date(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_assigned_to_operator_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_column('logs_date')
        batch_op.drop_column('assigned_date')

    # ### end Alembic commands ###
