"""little changes

Revision ID: d79b8f9e969e
Revises: ed13779cca0f
Create Date: 2024-05-03 12:55:01.671270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79b8f9e969e'
down_revision = 'ed13779cca0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_params_logs_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_params_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_params_logs_station_id'))

    # ### end Alembic commands ###
