"""Added the process_no in reasons table

Revision ID: dd8899334dd0
Revises: 79ca1d67fd94
Create Date: 2024-06-08 09:48:29.940295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8899334dd0'
down_revision = '79ca1d67fd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_no', sa.String(length=40), nullable=False))
        batch_op.create_index(batch_op.f('ix_reasons_process_no'), ['process_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reasons_process_no'))
        batch_op.drop_column('process_no')

    # ### end Alembic commands ###
