"""updated in all_operators_logged_in_status table

Revision ID: e7861599246a
Revises: 274823d8596a
Create Date: 2023-12-23 14:48:21.851562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7861599246a'
down_revision = '274823d8596a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_operators_logged_in_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_login_time', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_login_time', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('logout_time', sa.Date(), nullable=True))
        batch_op.drop_column('time')
        batch_op.drop_column('line_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_operators_logged_in_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_no', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('logout_time')
        batch_op.drop_column('last_login_time')
        batch_op.drop_column('first_login_time')

    # ### end Alembic commands ###
