"""apply indexing in fpa_and_set_up_approved_records table

Revision ID: f301e5b33b0e
Revises: 44c6aa7d21e9
Create Date: 2024-03-14 16:59:48.922398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f301e5b33b0e'
down_revision = '44c6aa7d21e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fpa_and_set_up_approved_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fpa_and_set_up_approved_records_operator_employee_id'), ['operator_employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fpa_and_set_up_approved_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fpa_and_set_up_approved_records_operator_employee_id'))
        batch_op.drop_index(batch_op.f('ix_fpa_and_set_up_approved_records_date'))

    # ### end Alembic commands ###
