"""little changes

Revision ID: f7578f2cd2e3
Revises: c65409eb184a
Create Date: 2024-05-03 11:41:13.129770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7578f2cd2e3'
down_revision = 'c65409eb184a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('failed_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('failed_items', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
